compile:
  # Choosing to run compilation tests on 2 different Arduino platforms
  platforms:
    - uno
    - due
    - zero
    - leonardo
#    - m4
    - esp32
#    - esp8266
    - mega2560
#    - nano_every

  # Declaring Dependent Arduino Libraries (to be installed via the Arduino Library Manager)
  libraries:
    - Servo
