; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extMINra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[Blink]
src_dir = $PROJECT_DIR/examples/01.Basics/Blink/
lib_dir = src
include_dir = src

[esp32-benchmark-callable-params]
src_dir = $PROJECT_DIR/examples/platformio/benchmark-callable-params/
lib_dir = src
include_dir = src


[env:uno]
platform = atmelavr
board = uno
framework = arduino
