# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := fixtures
ARDUINO_LIBS := AUnit Plaquette 
ARDUINO_LIB_DIRS := ../../..
include ../../libraries/EpoxyDuino/EpoxyDuino.mk
