var annotated_dup =
[
    [ "pq", null, [
      [ "AbstractChronometer", "classpq_1_1_abstract_chronometer.html", "classpq_1_1_abstract_chronometer" ],
      [ "AbstractField", "classpq_1_1_abstract_field.html", "classpq_1_1_abstract_field" ],
      [ "AbstractOscillator", "classpq_1_1_abstract_oscillator.html", "classpq_1_1_abstract_oscillator" ],
      [ "AbstractServoOut", "classpq_1_1_abstract_servo_out.html", "classpq_1_1_abstract_servo_out" ],
      [ "AbstractTimer", "classpq_1_1_abstract_timer.html", "classpq_1_1_abstract_timer" ],
      [ "AbstractWave", "classpq_1_1_abstract_wave.html", "classpq_1_1_abstract_wave" ],
      [ "Alarm", "classpq_1_1_alarm.html", "classpq_1_1_alarm" ],
      [ "AnalogIn", "classpq_1_1_analog_in.html", "classpq_1_1_analog_in" ],
      [ "AnalogOut", "classpq_1_1_analog_out.html", "classpq_1_1_analog_out" ],
      [ "AnalogSource", "classpq_1_1_analog_source.html", "classpq_1_1_analog_source" ],
      [ "Chainable", "classpq_1_1_chainable.html", "classpq_1_1_chainable" ],
      [ "Chronometer", "classpq_1_1_chronometer.html", "classpq_1_1_chronometer" ],
      [ "common_pair_type", "structpq_1_1common__pair__type.html", null ],
      [ "common_triple_type", "structpq_1_1common__triple__type.html", null ],
      [ "ContinuousServoOut", "classpq_1_1_continuous_servo_out.html", "classpq_1_1_continuous_servo_out" ],
      [ "Debounceable", "classpq_1_1_debounceable.html", "classpq_1_1_debounceable" ],
      [ "DigitalIn", "classpq_1_1_digital_in.html", "classpq_1_1_digital_in" ],
      [ "DigitalOut", "classpq_1_1_digital_out.html", "classpq_1_1_digital_out" ],
      [ "DigitalSource", "classpq_1_1_digital_source.html", "classpq_1_1_digital_source" ],
      [ "DigitalUnit", "classpq_1_1_digital_unit.html", "classpq_1_1_digital_unit" ],
      [ "Engine", "classpq_1_1_engine.html", "classpq_1_1_engine" ],
      [ "EventManager", "classpq_1_1_event_manager.html", "classpq_1_1_event_manager" ],
      [ "Metronome", "classpq_1_1_metronome.html", "classpq_1_1_metronome" ],
      [ "micro_seconds_t", "unionpq_1_1micro__seconds__t.html", null ],
      [ "MinMaxScaler", "classpq_1_1_min_max_scaler.html", "classpq_1_1_min_max_scaler" ],
      [ "MovingAverage", "classpq_1_1_moving_average.html", "classpq_1_1_moving_average" ],
      [ "MovingFilter", "classpq_1_1_moving_filter.html", "classpq_1_1_moving_filter" ],
      [ "MovingStats", "classpq_1_1_moving_stats.html", "classpq_1_1_moving_stats" ],
      [ "Normalizer", "classpq_1_1_normalizer.html", "classpq_1_1_normalizer" ],
      [ "PeakDetector", "classpq_1_1_peak_detector.html", "classpq_1_1_peak_detector" ],
      [ "PinConfig", "classpq_1_1_pin_config.html", "classpq_1_1_pin_config" ],
      [ "PivotField", "classpq_1_1_pivot_field.html", "classpq_1_1_pivot_field" ],
      [ "Ramp", "classpq_1_1_ramp.html", "classpq_1_1_ramp" ],
      [ "RobustScaler", "classpq_1_1_robust_scaler.html", "classpq_1_1_robust_scaler" ],
      [ "ServoOut", "classpq_1_1_servo_out.html", "classpq_1_1_servo_out" ],
      [ "SineWave", "classpq_1_1_sine_wave.html", "classpq_1_1_sine_wave" ],
      [ "Smoothable", "classpq_1_1_smoothable.html", "classpq_1_1_smoothable" ],
      [ "Smoother", "classpq_1_1_smoother.html", "classpq_1_1_smoother" ],
      [ "SquareWave", "classpq_1_1_square_wave.html", "classpq_1_1_square_wave" ],
      [ "StreamIn", "classpq_1_1_stream_in.html", "classpq_1_1_stream_in" ],
      [ "StreamOut", "classpq_1_1_stream_out.html", "classpq_1_1_stream_out" ],
      [ "Timeable", "classpq_1_1_timeable.html", "classpq_1_1_timeable" ],
      [ "TimeSliceField", "classpq_1_1_time_slice_field.html", "classpq_1_1_time_slice_field" ],
      [ "TimeWindowable", "classpq_1_1_time_windowable.html", "classpq_1_1_time_windowable" ],
      [ "TriangleWave", "classpq_1_1_triangle_wave.html", "classpq_1_1_triangle_wave" ],
      [ "Unit", "classpq_1_1_unit.html", "classpq_1_1_unit" ],
      [ "Wave", "classpq_1_1_wave.html", "classpq_1_1_wave" ]
    ] ],
    [ "HybridArrayList", "class_hybrid_array_list.html", "class_hybrid_array_list" ]
];