var annotated_dup =
[
    [ "pq", null, [
      [ "AbstractChronometer", "classpq_1_1_abstract_chronometer.html", "classpq_1_1_abstract_chronometer" ],
      [ "AbstractField", "classpq_1_1_abstract_field.html", "classpq_1_1_abstract_field" ],
      [ "AbstractOscillator", "classpq_1_1_abstract_oscillator.html", "classpq_1_1_abstract_oscillator" ],
      [ "AbstractServoOut", "classpq_1_1_abstract_servo_out.html", "classpq_1_1_abstract_servo_out" ],
      [ "AbstractTimer", "classpq_1_1_abstract_timer.html", "classpq_1_1_abstract_timer" ],
      [ "AbstractWave", "classpq_1_1_abstract_wave.html", "classpq_1_1_abstract_wave" ],
      [ "Alarm", "classpq_1_1_alarm.html", "classpq_1_1_alarm" ],
      [ "always_false", "structpq_1_1always__false.html", null ],
      [ "AnalogIn", "classpq_1_1_analog_in.html", "classpq_1_1_analog_in" ],
      [ "AnalogOut", "classpq_1_1_analog_out.html", "classpq_1_1_analog_out" ],
      [ "AnalogSource", "classpq_1_1_analog_source.html", "classpq_1_1_analog_source" ],
      [ "Chronometer", "classpq_1_1_chronometer.html", "classpq_1_1_chronometer" ],
      [ "common_pair_type", "structpq_1_1common__pair__type.html", null ],
      [ "common_triple_type", "structpq_1_1common__triple__type.html", null ],
      [ "ContinuousServoOut", "classpq_1_1_continuous_servo_out.html", "classpq_1_1_continuous_servo_out" ],
      [ "Debounceable", "classpq_1_1_debounceable.html", "classpq_1_1_debounceable" ],
      [ "DigitalIn", "classpq_1_1_digital_in.html", "classpq_1_1_digital_in" ],
      [ "DigitalOut", "classpq_1_1_digital_out.html", "classpq_1_1_digital_out" ],
      [ "DigitalSource", "classpq_1_1_digital_source.html", "classpq_1_1_digital_source" ],
      [ "DigitalUnit", "classpq_1_1_digital_unit.html", "classpq_1_1_digital_unit" ],
      [ "enable_if", "structpq_1_1enable__if.html", null ],
      [ "enable_if< true, T >", "structpq_1_1enable__if_3_01true_00_01_t_01_4.html", null ],
      [ "Engine", "classpq_1_1_engine.html", "classpq_1_1_engine" ],
      [ "EventManager", "classpq_1_1_event_manager.html", "classpq_1_1_event_manager" ],
      [ "flow_error", "structpq_1_1flow__error.html", null ],
      [ "Flowable", "classpq_1_1_flowable.html", "classpq_1_1_flowable" ],
      [ "HybridArrayList", "classpq_1_1_hybrid_array_list.html", "classpq_1_1_hybrid_array_list" ],
      [ "is_chainable", "structpq_1_1is__chainable.html", null ],
      [ "is_integral", "structpq_1_1is__integral.html", null ],
      [ "is_integral< bool >", "structpq_1_1is__integral_3_01bool_01_4.html", null ],
      [ "is_integral< char >", "structpq_1_1is__integral_3_01char_01_4.html", null ],
      [ "is_integral< int >", "structpq_1_1is__integral_3_01int_01_4.html", null ],
      [ "is_integral< long >", "structpq_1_1is__integral_3_01long_01_4.html", null ],
      [ "is_integral< long long >", "structpq_1_1is__integral_3_01long_01long_01_4.html", null ],
      [ "is_integral< short >", "structpq_1_1is__integral_3_01short_01_4.html", null ],
      [ "is_integral< signed char >", "structpq_1_1is__integral_3_01signed_01char_01_4.html", null ],
      [ "is_integral< unsigned char >", "structpq_1_1is__integral_3_01unsigned_01char_01_4.html", null ],
      [ "is_integral< unsigned int >", "structpq_1_1is__integral_3_01unsigned_01int_01_4.html", null ],
      [ "is_integral< unsigned long >", "structpq_1_1is__integral_3_01unsigned_01long_01_4.html", null ],
      [ "is_integral< unsigned long long >", "structpq_1_1is__integral_3_01unsigned_01long_01long_01_4.html", null ],
      [ "is_integral< unsigned short >", "structpq_1_1is__integral_3_01unsigned_01short_01_4.html", null ],
      [ "LabelView", "structpq_1_1_label_view.html", "structpq_1_1_label_view" ],
      [ "Metronome", "classpq_1_1_metronome.html", "classpq_1_1_metronome" ],
      [ "micro_seconds_t", "unionpq_1_1micro__seconds__t.html", null ],
      [ "MinMaxScaler", "classpq_1_1_min_max_scaler.html", "classpq_1_1_min_max_scaler" ],
      [ "Monitor", "classpq_1_1_monitor.html", "classpq_1_1_monitor" ],
      [ "MovingAverage", "classpq_1_1_moving_average.html", "classpq_1_1_moving_average" ],
      [ "MovingFilter", "classpq_1_1_moving_filter.html", "classpq_1_1_moving_filter" ],
      [ "MovingStats", "classpq_1_1_moving_stats.html", "classpq_1_1_moving_stats" ],
      [ "Normalizer", "classpq_1_1_normalizer.html", "classpq_1_1_normalizer" ],
      [ "NullPrint", "classpq_1_1_null_print.html", null ],
      [ "ParameterSlot", "classpq_1_1_parameter_slot.html", "classpq_1_1_parameter_slot" ],
      [ "PeakDetector", "classpq_1_1_peak_detector.html", "classpq_1_1_peak_detector" ],
      [ "PinConfig", "classpq_1_1_pin_config.html", "classpq_1_1_pin_config" ],
      [ "PivotField", "classpq_1_1_pivot_field.html", "classpq_1_1_pivot_field" ],
      [ "Plotter", "classpq_1_1_plotter.html", "classpq_1_1_plotter" ],
      [ "PlotterFormat", "structpq_1_1_plotter_format.html", "structpq_1_1_plotter_format" ],
      [ "Ramp", "classpq_1_1_ramp.html", "classpq_1_1_ramp" ],
      [ "remove_const", "structpq_1_1remove__const.html", null ],
      [ "remove_const< const T >", "structpq_1_1remove__const_3_01const_01_t_01_4.html", null ],
      [ "remove_cv", "structpq_1_1remove__cv.html", null ],
      [ "remove_cvref", "structpq_1_1remove__cvref.html", null ],
      [ "remove_reference", "structpq_1_1remove__reference.html", null ],
      [ "remove_reference< T & >", "structpq_1_1remove__reference_3_01_t_01_6_01_4.html", null ],
      [ "remove_volatile", "structpq_1_1remove__volatile.html", null ],
      [ "remove_volatile< volatile T >", "structpq_1_1remove__volatile_3_01volatile_01_t_01_4.html", null ],
      [ "RobustScaler", "classpq_1_1_robust_scaler.html", "classpq_1_1_robust_scaler" ],
      [ "ServoOut", "classpq_1_1_servo_out.html", "classpq_1_1_servo_out" ],
      [ "SineWave", "classpq_1_1_sine_wave.html", "classpq_1_1_sine_wave" ],
      [ "Smoothable", "classpq_1_1_smoothable.html", "classpq_1_1_smoothable" ],
      [ "Smoother", "classpq_1_1_smoother.html", "classpq_1_1_smoother" ],
      [ "SquareWave", "classpq_1_1_square_wave.html", "classpq_1_1_square_wave" ],
      [ "StreamIn", "classpq_1_1_stream_in.html", "classpq_1_1_stream_in" ],
      [ "StreamOut", "classpq_1_1_stream_out.html", "classpq_1_1_stream_out" ],
      [ "Timeable", "classpq_1_1_timeable.html", "classpq_1_1_timeable" ],
      [ "TimeSliceField", "classpq_1_1_time_slice_field.html", "classpq_1_1_time_slice_field" ],
      [ "TimeWindowable", "classpq_1_1_time_windowable.html", "classpq_1_1_time_windowable" ],
      [ "TriangleWave", "classpq_1_1_triangle_wave.html", "classpq_1_1_triangle_wave" ],
      [ "Unit", "classpq_1_1_unit.html", "classpq_1_1_unit" ],
      [ "Value", "classpq_1_1_value.html", "classpq_1_1_value" ],
      [ "ValueCodec", "structpq_1_1_value_codec.html", null ],
      [ "ValueCodec< bool >", "structpq_1_1_value_codec_3_01bool_01_4.html", null ],
      [ "ValueCodec< float >", "structpq_1_1_value_codec_3_01float_01_4.html", null ],
      [ "ValueCodec< int32_t >", "structpq_1_1_value_codec_3_01int32__t_01_4.html", null ],
      [ "Wave", "classpq_1_1_wave.html", "classpq_1_1_wave" ]
    ] ]
];