name: Compile Examples
on:
  push:
    paths:
    - '**.ino'
    - '**.cpp'
    - '**.h'
    - '**arduino-test-compile.yml'
  pull_request:
jobs:
  build:
    name: ${{ matrix.arduino-boards-fqbn }} - test compiling examples
    runs-on: ubuntu-latest
    env:
      REQUIRED_LIBRARIES: Servo
    strategy:
      matrix:
        arduino-boards-fqbn:
          - arduino:avr:uno
          - arduino:avr:leonardo
#          - esp32:esp32:featheresp32:FlashFreq=80

        include:
          - arduino-boards-fqbn: arduino:avr:uno

          - arduino-boards-fqbn: arduino:avr:leonardo
          
#          - arduino-boards-fqbn: esp32:esp32:featheresp32:FlashFreq=80
#            platform-url: https://dl.espressif.com/dl/package_esp32_index.json 
#            required-libraries: ESP32 AnalogWrite

      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile all examples
        uses: ArminJo/arduino-test-compile@v3
        with:
          arduino-board-fqbn: ${{ matrix.arduino-boards-fqbn }}
          platform-default-url: ${{ env.PLATFORM_DEFAULT_URL }}
          platform-url: ${{ matrix.platform-url }}
          required-libraries: ${{ env.REQUIRED_LIBRARIES }},${{ matrix.required-libraries }}
          sketch-names: ${{ matrix.sketch-names }}
          sketches-exclude: ${{ matrix.sketches-exclude }}
          build-properties: ${{ toJson(matrix.build-properties) }}
          sketch-names-find-start: examples/
