name: LibraryBuild
on: [push, pull_request]
jobs:
  build:
    name: Test compiling examples
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Compile all examples
        uses: ArminJo/arduino-test-compile@v3
      with:
        arduino-board-fqbn: arduino:avr:uno
        required-libraries: Servo
